# Optimization rule for mhbos table
# Replaces text file reading with direct JDBC reading

# Enable/disable this rule
enabled: true


# Parameters for the generate_jdbc_read action
parameters:
  source: default


rules:
  drop_partition:
    enabled: true
    trigger:
      node_type: "Alter"
    action:
      type: "skip"

  drop_external_table:
    enabled: true
    trigger:
      node_type: "Drop"
      table_name_suffix:
        - "_et"
    action:
      type: "skip"

#  replace_external_table_file_path:
#    enabled: true
##     Condition to trigger the rule
#    trigger:
#      node_type: "Create"
#      table_properties:
#        - "STORED AS TEXTFILE"
#      read_from_text_file: true
#
##     Action
#    action:
#      type: "replace_external_table_file_path"


  create_external_table:
    enabled: true
    # Condition to trigger the rule
    trigger:
      node_type: "Create"
      table_properties:
        - "STORED AS TEXTFILE"
      read_from_text_file: false

    # Action
    action:
      type: "generate_jdbc_read"

      # Parameters for the generate_jdbc_read action
      parameters:
        # Name of the table in the source database
        schema: dbo
        port: 1433

        # Variable containing the connection URL (will be used in Jinja template)
        jdbc_url_variable: "jdbc_url"

        # query_template will automatically fill columns based on the CREATE TABLE statement
        default_query_template: "SELECT\n    {columns}\nFROM {source_db_table} (NOLOCK)\nWHERE 1 = 1"


  insert_into_raw_table:
    enabled: true
    trigger:
      node_type: "Insert"
    action:
      type: "skip"
