/* 1.2 Drop all temporary tables at the start of the program */
DROP TABLE IF EXISTS {params["com_schema"]}.temp_t_mhbos_m_client_all



/* 2.1 Create a temporary table temp_com_mhbos_m_client_all to store the current vaild data */
CREATE TABLE IF NOT EXISTS {params["com_schema"]}.temp_t_mhbos_m_client_all (
  `client_no` STRING,
  `client_group` STRING,
  `cds_acc_no` STRING,
  `tdr_code` STRING,
  `client_name` STRING,
  `client_type` STRING,
  `margin` STRING,
  `last_margin_date` TIMESTAMP,
  `int_rate` DECIMAL(5, 2),
  `auto_ded` STRING,
  `despatch_mode` STRING,
  `copies` DECIMAL(2, 0),
  `prohibit_trade` STRING,
  `custody_status` STRING,
  `race` STRING,
  `country` STRING,
  `ic_no_new` STRING,
  `ic_no_old` STRING,
  `margin_limit` DECIMAL(9, 0),
  `margin_pct` DECIMAL(5, 2),
  `rollover_rate` DECIMAL(6, 3),
  `form_completed` STRING,
  `last_tran_date` TIMESTAMP,
  `ytd_bvalue` DECIMAL(12, 2),
  `ytd_svalue` DECIMAL(12, 2),
  `ytd_brokerage` DECIMAL(11, 2),
  `os_led_bal` DECIMAL(12, 2),
  `title` STRING,
  `addr1` STRING,
  `addr2` STRING,
  `addr3` STRING,
  `tel_no_home` STRING,
  `tel_no_office` STRING,
  `date_created` TIMESTAMP,
  `stop_payt` STRING,
  `acc_payee` STRING,
  `category` STRING,
  `fax_no` STRING,
  `auto_contra` STRING,
  `pnl_acc_no` STRING,
  `cr_limit` DECIMAL(9, 0),
  `trust_bal` DECIMAL(12, 2),
  `avg_ind` STRING,
  `remarks` STRING,
  `contact_person` STRING,
  `date_closed` TIMESTAMP,
  `grace_period` DECIMAL(3, 0),
  `acct_type` DECIMAL(2, 0),
  `assoc_ind` STRING,
  `short_sell_ind` STRING,
  `short_name` STRING,
  `mesdaq_pctlmt` DECIMAL(5, 2),
  `date_change` TIMESTAMP,
  `resi_code` STRING,
  `sex` STRING,
  `charge_int` STRING,
  `bdebt` STRING,
  `assets` DECIMAL(12, 2),
  `liabilities` DECIMAL(12, 2),
  `income` DECIMAL(12, 2),
  `expenses` DECIMAL(12, 2),
  `bdebt_his_ind` STRING,
  `rel_ac1` STRING,
  `rel_ac2` STRING,
  `rel_ac3` STRING,
  `rel_ac4` STRING,
  `occupation` STRING,
  `margin_int` DECIMAL(12, 2),
  `lst_led_no` DECIMAL(9, 0),
  `cur_led_no` DECIMAL(9, 0),
  `remarks2` STRING,
  `acc_type` STRING,
  `mas_accno` STRING,
  `legal` STRING,
  `sell_limit` DECIMAL(9, 0),
  `brk_rate` DECIMAL(9, 4),
  `client_name1` STRING,
  `postcode` STRING,
  `brokerage_type` STRING,
  `cds_acc_no1` STRING,
  `remarks1` STRING,
  `payment_bank_code` STRING,
  `noms` STRING,
  `dms_date` TIMESTAMP,
  `violation_date` TIMESTAMP,
  `mcd_branch` STRING,
  `home_branch` STRING,
  `eaf_code` STRING,
  `call_warrant` STRING,
  `user_id` STRING,
  `credit_int_rate` DECIMAL(5, 2),
  `min_eligible_amt` DECIMAL(18, 4),
  `intraday_flag` STRING,
  `intraday_rate` DECIMAL(5, 4),
  `cta_weight` DECIMAL(3, 0),
  `sta_weight` DECIMAL(3, 0),
  `bo_cds_acc_no` STRING,
  `ecos_form` STRING,
  `custodian_no` STRING,
  `prin_acc` STRING,
  `armada_type` STRING,
  `old_authorisee` STRING,
  `etrade_rate` DECIMAL(9, 4),
  `etf` STRING,
  `cstamp_client_exempt` STRING,
  `main_branch` STRING,
  `prev_client_no` STRING,
  `web_eds` STRING,
  `place` STRING,
  `addr4` STRING,
  `excl_tdr_deduct` STRING,
  `excl_auto_susp` STRING,
  `trust_flag` STRING,
  `mgn_new_int_rate` DECIMAL(5, 2),
  `counter_concentration` DECIMAL(5, 2),
  `auto_trust` STRING,
  `margin_pct2` DECIMAL(5, 2),
  `df_flag` STRING,
  `mgn_curr_int_rate` DECIMAL(5, 2),
  `product_type` STRING,
  `web_ecos` STRING,
  `xeye_clt_grp` STRING,
  `bursa_violation_date` TIMESTAMP,
  `client_name2` STRING,
  `brokerage_type_etrade` STRING,
  `brokerage_type_odd_lot` STRING,
  `omnibus` STRING,
  `cg_tdr_code` STRING,
  `limit_foreign` DECIMAL(9, 4),
  `limit_bursa` DECIMAL(9, 4),
  `brokerage_type_intraday` STRING,
  `brokerage_type_intraday_etrade` STRING,
  `bursa_violation_date1` TIMESTAMP,
  `cif_no` STRING,
  `brokerage_type_foreign` STRING,
  `soft_copy` STRING,
  `exclude_rollover` STRING,
  `account_status` STRING,
  `w8ben` STRING,
  `ic_no_rel1` STRING,
  `ic_no_rel2` STRING,
  `ic_no_rel3` STRING,
  `ic_no_rel4` STRING,
  `ic_no_rel5` STRING,
  `rel1` STRING,
  `rel2` STRING,
  `rel3` STRING,
  `rel4` STRING,
  `rel5` STRING,
  `brokerage_type_etrade_b` STRING,
  `brokerage_type_odd_lot_b` STRING,
  `brokerage_type_b` STRING,
  `brokerage_type_foreign_b` STRING,
  `brokerage_type_intraday_b` STRING,
  `brokerage_type_intraday_etrade_b` STRING,
  `brokerage_type_etrade_s` STRING,
  `brokerage_type_odd_lot_s` STRING,
  `brokerage_type_s` STRING,
  `brokerage_type_foreign_s` STRING,
  `brokerage_type_intraday_s` STRING,
  `brokerage_type_intraday_etrade_s` STRING,
  `no_free_trade` DECIMAL(2, 0),
  `sms` STRING,
  `mobile_prefix` STRING,
  `mobile_no` STRING,
  `foreign_curr_set` STRING,
  `num_free_trade` DECIMAL(2, 0),
  `etrader_type` STRING,
  `check_limit` STRING,
  `auto_margin` STRING,
  `margin_client_no` STRING,
  `dup_despatch_mode` STRING,
  `risk` STRING,
  `exclude_trader_limit` STRING,
  `sett_mode_date_change` TIMESTAMP,
  `pick_up_fee_pct` DECIMAL(5, 2),
  `e_payment` STRING,
  `mgn_new_int_rate2` DECIMAL(5, 2),
  `fund_cost_type` STRING,
  `check_share` STRING,
  `citibank_changes` STRING,
  `citibank_charges` STRING,
  `cq_market` STRING,
  `exclude_margin_pro_rate` STRING,
  `brokerage_type_cash_b` STRING,
  `brokerage_type_etrade_cash_b` STRING,
  `clt_consent` STRING,
  `consent_start_date` TIMESTAMP,
  `portfolio` STRING,
  `expiry_date` TIMESTAMP,
  `intraday_auto_contra_option` STRING,
  `dcf_limit` DECIMAL(9, 0),
  `brokerage_type_etb` STRING,
  `mgn_force_sell_pct` DECIMAL(5, 2),
  `mgn_tenure` DECIMAL(3, 0),
  `mgn_expiry_date` TIMESTAMP,
  `loss_gl_acc_no` STRING,
  `portfolio_date` TIMESTAMP,
  `day_prior_temp_susp` DECIMAL(4, 0),
  `day_prior_perm_susp` DECIMAL(4, 0),
  `gst_code` STRING,
  `match_price_decimal_local` DECIMAL(1, 0),
  `match_price_decimal_foreign` DECIMAL(1, 0),
  `id_type` STRING,
  `primary_id_expiry_date` TIMESTAMP,
  `secondary_id_no` STRING,
  `secondary_id_expiry_date` TIMESTAMP,
  `mgn_int_tdr_spread_pct` DECIMAL(5, 2),
  `mgn_base_int_rate` DECIMAL(5, 2),
  `mgn_int_tdr_share` DECIMAL(5, 2),
  `islamic_flag` STRING,
  `mcd_resident_flag` STRING,
  `chq_charges_flag` STRING,
  `chq_charges_tdr_pct` DECIMAL(9, 2),
  `brokerage_type_foreign_etrade` STRING,
  `brokerage_type_foreign_etrade_b` STRING,
  `brokerage_type_foreign_etrade_s` STRING,
  `grp_exch_code` STRING,
  `secondary_id_type` STRING,
  `bdebt_ras` STRING,
  `twse_declaration` STRING,
  `client_name3` STRING,
  `joint_acc_amt` DECIMAL(12, 2),
  `high_risk_market` STRING,
  `brokerage_type_leap_normal` STRING,
  `brokerage_type_leap_etrade` STRING,
  `etl_timestamp` STRING,
  `etl_dt` STRING,
  `part_id` STRING,
  `date_of_birth` TIMESTAMP,
  `email` STRING,
  `perm_addr1` STRING,
  `perm_addr2` STRING,
  `perm_addr3` STRING,
  `perm_addr4` STRING,
  `perm_postcode` STRING,
  `perm_city` STRING, /* 20250715 */
  `perm_state_code` STRING, /* 20250715 */
  `perm_country` STRING, /* 20250715 */
  `type_of_account` STRING, /* 20250806 */
  `einvoice_email` STRING, /* 20250903 */
  `state_code` STRING /* 20251013 */
)

TRUNCATE TABLE   {params["com_schema"]}.temp_t_mhbos_m_client_all

WITH filtered_clients AS (
  SELECT DISTINCT
    client_no
  FROM {params["com_schema"]}.r_mhbos_m_client
  WHERE
    part_id = '{batch_date}'
  UNION
  SELECT DISTINCT
    client_no
  FROM {params["com_schema"]}.r_mhbos_m_client_ext
  WHERE
    part_id = '{batch_date}'
), latest_clients AS (
  SELECT
    mmc.*,
    ROW_NUMBER() OVER (PARTITION BY mmc.client_no ORDER BY mmc.part_id DESC) AS rn
  FROM {params["com_schema"]}.r_mhbos_m_client AS mmc
  INNER JOIN filtered_clients AS fc
    ON mmc.client_no = fc.client_no
  WHERE
    mmc.part_id <= '{batch_date}'
)
INSERT INTO {params["com_schema"]}.temp_t_mhbos_m_client_all
SELECT
  mmc.client_no,
  mmc.client_group,
  mmc.cds_acc_no,
  mmc.tdr_code,
  mmc.client_name,
  mmc.client_type,
  mmc.margin,
  mmc.last_margin_date,
  mmc.int_rate,
  mmc.auto_ded,
  mmc.despatch_mode,
  mmc.copies,
  mmc.prohibit_trade,
  mmc.custody_status,
  mmc.race,
  mmc.country,
  REGEXP_REPLACE(mmc.ic_no_new, '-', '') AS ic_no_new,
  REGEXP_REPLACE(mmc.ic_no_old, '-', '') AS ic_no_old,
  mmc.margin_limit,
  mmc.margin_pct,
  mmc.rollover_rate,
  mmc.form_completed,
  mmc.last_tran_date,
  mmc.ytd_bvalue,
  mmc.ytd_svalue,
  mmc.ytd_brokerage,
  mmc.os_led_bal,
  mmc.title,
  mmc.addr1,
  mmc.addr2,
  mmc.addr3,
  mmc.tel_no_home,
  mmc.tel_no_office,
  mmc.date_created,
  mmc.stop_payt,
  mmc.acc_payee,
  mmc.category,
  mmc.fax_no,
  mmc.auto_contra,
  mmc.pnl_acc_no,
  mmc.cr_limit,
  mmc.trust_bal,
  mmc.avg_ind,
  mmc.remarks,
  mmc.contact_person,
  mmc.date_closed,
  mmc.grace_period,
  mmc.acct_type,
  mmc.assoc_ind,
  mmc.short_sell_ind,
  mmc.short_name,
  mmc.mesdaq_pctlmt,
  mmc.date_change,
  mmc.resi_code,
  mmc.sex,
  mmc.charge_int,
  mmc.bdebt,
  mmc.assets,
  mmc.liabilities,
  mmc.income,
  mmc.expenses,
  mmc.bdebt_his_ind,
  mmc.rel_ac1,
  mmc.rel_ac2,
  mmc.rel_ac3,
  mmc.rel_ac4,
  mmc.occupation,
  mmc.margin_int,
  mmc.lst_led_no,
  mmc.cur_led_no,
  mmc.remarks2,
  mmc.acc_type,
  mmc.mas_accno,
  mmc.legal,
  mmc.sell_limit,
  mmc.brk_rate,
  mmc.client_name1,
  mmc.postcode,
  mmc.brokerage_type,
  mmc.cds_acc_no1,
  mmc.remarks1,
  mmc.payment_bank_code,
  mmc.noms,
  mmc.dms_date,
  mmc.violation_date,
  mmc.mcd_branch,
  mmc.home_branch,
  mmc.eaf_code,
  mmc.call_warrant,
  mmc.`user_id`,
  mmc.credit_int_rate,
  mmc.min_eligible_amt,
  mmc.intraday_flag,
  mmc.intraday_rate,
  mmc.cta_weight,
  mmc.sta_weight,
  mmc.bo_cds_acc_no,
  mmc.ecos_form,
  mmc.custodian_no,
  mmc.prin_acc,
  mmc.armada_type,
  mmc.old_authorisee,
  mmc.etrade_rate,
  mmc.etf,
  mmc.cstamp_client_exempt,
  mmc.main_branch,
  mmc.prev_client_no,
  mmc.web_eds,
  mmc.place,
  mmc.addr4,
  mmc.excl_tdr_deduct,
  mmc.excl_auto_susp,
  mmc.trust_flag,
  mmc.mgn_new_int_rate,
  mmc.counter_concentration,
  mmc.auto_trust,
  mmc.margin_pct2,
  mmc.df_flag,
  mmc.mgn_curr_int_rate,
  mmc.product_type,
  mmc.web_ecos,
  mmc.xeye_clt_grp,
  mmc.bursa_violation_date,
  mmc.client_name2,
  mmc.brokerage_type_etrade,
  mmc.brokerage_type_odd_lot,
  mmc.omnibus,
  mmc.cg_tdr_code,
  mmc.limit_foreign,
  mmc.limit_bursa,
  mmc.brokerage_type_intraday,
  mmc.brokerage_type_intraday_etrade,
  mmc.bursa_violation_date1,
  mmc.cif_no,
  mmc.brokerage_type_foreign,
  mmc.soft_copy,
  mmc.exclude_rollover,
  mmc.account_status,
  mmc.w8ben,
  mmc.ic_no_rel1,
  mmc.ic_no_rel2,
  mmc.ic_no_rel3,
  mmc.ic_no_rel4,
  mmc.ic_no_rel5,
  mmc.rel1,
  mmc.rel2,
  mmc.rel3,
  mmc.rel4,
  mmc.rel5,
  mmc.brokerage_type_etrade_b,
  mmc.brokerage_type_odd_lot_b,
  mmc.brokerage_type_b,
  mmc.brokerage_type_foreign_b,
  mmc.brokerage_type_intraday_b,
  mmc.brokerage_type_intraday_etrade_b,
  mmc.brokerage_type_etrade_s,
  mmc.brokerage_type_odd_lot_s,
  mmc.brokerage_type_s,
  mmc.brokerage_type_foreign_s,
  mmc.brokerage_type_intraday_s,
  mmc.brokerage_type_intraday_etrade_s,
  mmc.no_free_trade,
  mmc.sms,
  mmc.mobile_prefix,
  mmc.mobile_no,
  mmc.foreign_curr_set,
  mmc.num_free_trade,
  mmc.etrader_type,
  mmc.check_limit,
  mmc.auto_margin,
  mmc.margin_client_no,
  mmc.dup_despatch_mode,
  mmc.risk,
  mmc.exclude_trader_limit,
  mmc.sett_mode_date_change,
  mmc.pick_up_fee_pct,
  mmc.e_payment,
  mmc.mgn_new_int_rate2,
  mmc.fund_cost_type,
  mmc.check_share,
  mmc.citibank_changes,
  mmc.citibank_charges,
  mmc.cq_market,
  mmc.exclude_margin_pro_rate,
  mmc.brokerage_type_cash_b,
  mmc.brokerage_type_etrade_cash_b,
  mmc.clt_consent,
  mmc.consent_start_date,
  mmc.portfolio,
  mmc.expiry_date,
  mmc.intraday_auto_contra_option,
  mmc.dcf_limit,
  mmc.brokerage_type_etb,
  mmc.mgn_force_sell_pct,
  mmc.mgn_tenure,
  mmc.mgn_expiry_date,
  mmc.loss_gl_acc_no,
  mmc.portfolio_date,
  mmc.day_prior_temp_susp,
  mmc.day_prior_perm_susp,
  mmc.gst_code,
  mmc.match_price_decimal_local,
  mmc.match_price_decimal_foreign,
  mmc.id_type,
  mmc.primary_id_expiry_date,
  REGEXP_REPLACE(mmc.secondary_id_no, '-', '') AS secondary_id_no,
  mmc.secondary_id_expiry_date,
  mmc.mgn_int_tdr_spread_pct,
  mmc.mgn_base_int_rate,
  mmc.mgn_int_tdr_share,
  mmc.islamic_flag,
  mmc.mcd_resident_flag,
  mmc.chq_charges_flag,
  mmc.chq_charges_tdr_pct,
  mmc.brokerage_type_foreign_etrade,
  mmc.brokerage_type_foreign_etrade_b,
  mmc.brokerage_type_foreign_etrade_s,
  mmc.grp_exch_code,
  mmc.secondary_id_type,
  mmc.bdebt_ras,
  mmc.twse_declaration,
  mmc.client_name3,
  mmc.joint_acc_amt,
  mmc.high_risk_market,
  mmc.brokerage_type_leap_normal,
  mmc.brokerage_type_leap_etrade,
  mmc.etl_timestamp,
  mmc.etl_dt,
  mmc.part_id,
  mmce.date_of_birth,
  mmce.email,
  mmce.perm_addr1,
  mmce.perm_addr2,
  mmce.perm_addr3,
  mmce.perm_addr4,
  mmce.perm_postcode,
  mmce.perm_city /* 20250715 */,
  mmce.perm_state_code /* 20250715 */,
  mmce.perm_country /* 20250715 */,
  mmc.type_of_account /* 20250806 */,
  mmce.einvoice_email /* 20250903 */,
  mmce.state_code /* 20251013 */
FROM latest_clients AS mmc
LEFT JOIN {params["com_schema"]}.t_mhbos_m_client_ext AS mmce
  ON mmc.client_no = mmce.client_no AND mmce.part_id = '{batch_date}'
WHERE
  mmc.rn = 1
