-- Purpose:    ddl/cur
-- Author:     Sunline
-- Usage:      python $ETL_HOME/script/init.py com t_mhbos_m_client
-- CreateDate: 20180515
-- FileType:   DDL
--Logs:         sunlinedata     20230911        create table Version: 1.0
--Logs:         syhmi           20250903        added "einvoice_email" column

drop table if exists ${com_schema}.t_mhbos_m_client;

create table ${com_schema}.t_mhbos_m_client(
    client_no varchar(9) comment ''
    ,clean_rule_flag varchar(60) comment '1-primary_identification_type_flag
2-primary_identification_no_flag
3-secondary_identification_type_flag
4-secondary_identification_no_flag
5-client_name_flag
6-client_name1_flag
7-client_name2_flag
8-client_name4_flag
9-mobile_no_flag
10-fax_no_flag
11-tel_no_home_flag
12-tel_no_office_flag
13-date_of_birth_flag
14-race_flag
15-email_flag
16-sex_flag'
    ,primary_identification_type varchar(10) comment ''
    ,primary_identification_no varchar(60) comment ''
    ,secondary_identification_type varchar(10) comment ''
    ,secondary_identification_no varchar(60) comment ''
    ,customer_name varchar(250) comment ''
    ,customer_name_concatenate varchar(250) comment ''
    ,client_name varchar(60) comment ''
    ,client_name1 varchar(60) comment ''
    ,client_name2 varchar(60) comment ''
    ,client_name3 varchar(60) comment ''
    ,mobile_no varchar(20) comment ''
    ,fax_no varchar(20) comment ''
    ,tel_no_home varchar(20) comment ''
    ,tel_no_office varchar(20) comment ''
    ,date_of_birth timestamp comment ''
    ,race varchar(30) comment ''
    ,email_1 varchar(300) comment ''
    ,email_2 varchar(300) comment ''
    ,email_3 varchar(300) comment ''
    ,email_4 varchar(300) comment '' 
    ,email_5 varchar(300) comment ''
    ,email_6 varchar(300) comment ''
    ,email_7 varchar(300) comment ''
    ,email_8 varchar(300) comment ''
    ,email_9 varchar(300) comment '' 
    ,email_10 varchar(300) comment ''
    ,sex varchar(10) comment ''
    ,addr1 varchar(45) comment ''
    ,addr2 varchar(45) comment ''
    ,addr3 varchar(45) comment ''
    ,addr4 varchar(45) comment ''
    ,postcode varchar(6) comment ''
    ,city varchar(255) comment ''
    ,state varchar(50) comment ''
    ,perm_addr1 varchar(45) comment ''
    ,perm_addr2 varchar(45) comment ''
    ,perm_addr3 varchar(45) comment ''
    ,perm_addr4 varchar(45) comment ''
    ,perm_postcode varchar(6) comment ''
    ,perm_city varchar(255) comment ''
    ,perm_state varchar(50) comment ''
    ,noms_ind varchar(1) comment ''
    ,cleaned_nominees_name varchar(300) comment ''
    ,principal_name varchar(300) comment ''
    ,intermediary_name varchar(300) comment ''
    ,beneficiary_name varchar(300) comment ''
    ,nominees_type	varchar(10) comment ''
    ,pledged_securities_flag	varchar(1) comment ''  
    ,id_type	varchar(10) comment ''
    ,ic_no_new varchar(15) comment ''
    ,ic_no_old varchar(14) comment ''
    ,secondary_id_type varchar(2) comment ''
    ,secondary_id_no varchar(15) comment ''
    ,source_client_name varchar(50) comment ''
    ,source_client_name1 varchar(50) comment ''
    ,source_client_name2 varchar(50) comment ''
    ,source_client_name3 varchar(50) comment ''
    ,source_mobile_no varchar(15) comment ''
    ,source_fax_no varchar(15) comment ''
    ,source_tel_no_home varchar(15) comment ''
    ,source_tel_no_office varchar(15) comment ''
    ,source_date_of_birth timestamp comment ''
    ,source_race varchar(20) comment ''
    ,source_email varchar(300) comment ''
    ,source_sex varchar(10) comment ''
    ,client_group varchar(14) comment ''
    ,cds_acc_no varchar(9) comment ''
    ,tdr_code varchar(5) comment ''
    ,client_type varchar(3) comment ''
    ,margin varchar(1) comment ''
    ,last_margin_date timestamp comment ''
    ,int_rate numeric(5,2) comment ''
    ,auto_ded varchar(1) comment ''
    ,despatch_mode varchar(2) comment ''
    ,copies numeric(2,0) comment ''
    ,prohibit_trade varchar(1) comment ''
    ,custody_status varchar(1) comment ''
    ,country varchar(3) comment ''
    ,margin_limit numeric(9,0) comment ''
    ,margin_pct numeric(5,2) comment ''
    ,rollover_rate numeric(6,3) comment ''
    ,form_completed varchar(1) comment ''
    ,last_tran_date timestamp comment ''
    ,ytd_bvalue numeric(12,2) comment ''
    ,ytd_svalue numeric(12,2) comment ''
    ,ytd_brokerage numeric(11,2) comment ''
    ,os_led_bal numeric(12,2) comment ''
    ,title varchar(20) comment ''
    ,date_created timestamp comment ''
    ,stop_payt varchar(1) comment ''
    ,acc_payee varchar(100) comment ''
    ,category varchar(1) comment ''
    ,auto_contra varchar(1) comment ''
    ,pnl_acc_no varchar(18) comment ''
    ,cr_limit numeric(9,0) comment ''
    ,trust_bal numeric(12,2) comment ''
    ,avg_ind varchar(8) comment ''
    ,remarks varchar(60) comment ''
    ,contact_person varchar(40) comment ''
    ,date_closed timestamp comment ''
    ,grace_period numeric(3,0) comment ''
    ,acct_type numeric(2,0) comment ''
    ,assoc_ind varchar(1) comment ''
    ,short_sell_ind varchar(1) comment ''
    ,short_name varchar(10) comment ''
    ,mesdaq_pctlmt numeric(5,2) comment ''
    ,date_change timestamp comment ''
    ,resi_code varchar(5) comment ''
    ,charge_int varchar(1) comment ''
    ,bdebt varchar(1) comment ''
    ,assets numeric(12,2) comment ''
    ,liabilities numeric(12,2) comment ''
    ,income numeric(12,2) comment ''
    ,expenses numeric(12,2) comment ''
    ,bdebt_his_ind varchar(3) comment ''
    ,rel_ac1 varchar(9) comment ''
    ,rel_ac2 varchar(9) comment ''
    ,rel_ac3 varchar(9) comment ''
    ,rel_ac4 varchar(9) comment ''
    ,occupation varchar(60) comment ''
    ,margin_int numeric(12,2) comment ''
    ,lst_led_no numeric(9,0) comment ''
    ,cur_led_no numeric(9,0) comment ''
    ,remarks2 varchar(60) comment ''
    ,acc_type varchar(1) comment ''
    ,mas_accno varchar(9) comment ''
    ,legal varchar(1) comment ''
    ,sell_limit numeric(9,0) comment ''
    ,brk_rate numeric(9,4) comment ''
    ,brokerage_type varchar(3) comment ''
    ,cds_acc_no1 varchar(9) comment ''
    ,remarks1 varchar(60) comment ''
    ,payment_bank_code varchar(5) comment ''
    ,noms varchar(1) comment ''
    ,dms_date timestamp comment ''
    ,violation_date timestamp comment ''
    ,mcd_branch varchar(3) comment ''
    ,home_branch varchar(3) comment ''
    ,eaf_code varchar(1) comment ''
    ,call_warrant varchar(1) comment ''
    ,user_id varchar(20) comment ''
    ,credit_int_rate numeric(5,2) comment ''
    ,min_eligible_amt numeric(18,4) comment ''
    ,intraday_flag varchar(1) comment ''
    ,intraday_rate numeric(5,4) comment ''
    ,cta_weight numeric(3,0) comment ''
    ,sta_weight numeric(3,0) comment ''
    ,bo_cds_acc_no varchar(20) comment ''
    ,ecos_form varchar(1) comment ''
    ,custodian_no varchar(7) comment ''
    ,prin_acc varchar(2) comment ''
    ,armada_type varchar(8) comment ''
    ,old_authorisee varchar(5) comment ''
    ,etrade_rate numeric(9,4) comment ''
    ,etf varchar(1) comment ''
    ,cstamp_client_exempt varchar(1) comment ''
    ,main_branch varchar(3) comment ''
    ,prev_client_no varchar(9) comment ''
    ,web_eds varchar(1) comment ''
    ,place varchar(5) comment ''
    ,excl_tdr_deduct varchar(1) comment ''
    ,excl_auto_susp varchar(1) comment ''
    ,trust_flag varchar(1) comment ''
    ,mgn_new_int_rate numeric(5,2) comment ''
    ,counter_concentration numeric(5,2) comment ''
    ,auto_trust varchar(1) comment ''
    ,margin_pct2 numeric(5,2) comment ''
    ,df_flag varchar(1) comment ''
    ,mgn_curr_int_rate numeric(5,2) comment ''
    ,product_type varchar(1) comment ''
    ,web_ecos varchar(1) comment ''
    ,xeye_clt_grp varchar(14) comment ''
    ,bursa_violation_date timestamp comment ''
    ,brokerage_type_etrade varchar(3) comment ''
    ,brokerage_type_odd_lot varchar(3) comment ''
    ,omnibus varchar(1) comment ''
    ,cg_tdr_code varchar(7) comment ''
    ,limit_foreign numeric(9,4) comment ''
    ,limit_bursa numeric(9,4) comment ''
    ,brokerage_type_intraday varchar(3) comment ''
    ,brokerage_type_intraday_etrade varchar(3) comment ''
    ,bursa_violation_date1 timestamp comment ''
    ,cif_no varchar(20) comment ''
    ,brokerage_type_foreign varchar(3) comment ''
    ,soft_copy varchar(1) comment ''
    ,exclude_rollover varchar(1) comment ''
    ,account_status varchar(1) comment ''
    ,w8ben varchar(1) comment ''
    ,ic_no_rel1 varchar(15) comment ''
    ,ic_no_rel2 varchar(15) comment ''
    ,ic_no_rel3 varchar(15) comment ''
    ,ic_no_rel4 varchar(15) comment ''
    ,ic_no_rel5 varchar(15) comment ''
    ,rel1 varchar(15) comment ''
    ,rel2 varchar(15) comment ''
    ,rel3 varchar(15) comment ''
    ,rel4 varchar(15) comment ''
    ,rel5 varchar(15) comment ''
    ,brokerage_type_etrade_b varchar(3) comment ''
    ,brokerage_type_odd_lot_b varchar(3) comment ''
    ,brokerage_type_b varchar(3) comment ''
    ,brokerage_type_foreign_b varchar(3) comment ''
    ,brokerage_type_intraday_b varchar(3) comment ''
    ,brokerage_type_intraday_etrade_b varchar(3) comment ''
    ,brokerage_type_etrade_s varchar(3) comment ''
    ,brokerage_type_odd_lot_s varchar(3) comment ''
    ,brokerage_type_s varchar(3) comment ''
    ,brokerage_type_foreign_s varchar(3) comment ''
    ,brokerage_type_intraday_s varchar(3) comment ''
    ,brokerage_type_intraday_etrade_s varchar(3) comment ''
    ,no_free_trade numeric(2,0) comment ''
    ,sms varchar(1) comment ''
    ,mobile_prefix varchar(5) comment ''
    ,foreign_curr_set varchar(1) comment ''
    ,num_free_trade numeric(2,0) comment ''
    ,etrader_type varchar(2) comment ''
    ,check_limit varchar(1) comment ''
    ,auto_margin varchar(1) comment ''
    ,margin_client_no varchar(9) comment ''
    ,dup_despatch_mode varchar(1) comment ''
    ,risk varchar(1) comment ''
    ,exclude_trader_limit varchar(1) comment ''
    ,sett_mode_date_change timestamp comment ''
    ,pick_up_fee_pct numeric(5,2) comment ''
    ,e_payment varchar(1) comment ''
    ,mgn_new_int_rate2 numeric(5,2) comment ''
    ,fund_cost_type varchar(1) comment ''
    ,check_share varchar(1) comment ''
    ,citibank_changes varchar(1) comment ''
    ,citibank_charges varchar(1) comment ''
    ,cq_market varchar(1) comment ''
    ,exclude_margin_pro_rate varchar(1) comment ''
    ,brokerage_type_cash_b varchar(3) comment ''
    ,brokerage_type_etrade_cash_b varchar(3) comment ''
    ,clt_consent varchar(1) comment ''
    ,consent_start_date timestamp comment ''
    ,portfolio varchar(1) comment ''
    ,expiry_date timestamp comment ''
    ,intraday_auto_contra_option varchar(1) comment ''
    ,dcf_limit numeric(9,0) comment ''
    ,brokerage_type_etb varchar(3) comment ''
    ,mgn_force_sell_pct numeric(5,2) comment ''
    ,mgn_tenure numeric(3,0) comment ''
    ,mgn_expiry_date timestamp comment ''
    ,loss_gl_acc_no varchar(18) comment ''
    ,portfolio_date timestamp comment ''
    ,day_prior_temp_susp numeric(4,0) comment ''
    ,day_prior_perm_susp numeric(4,0) comment ''
    ,gst_code varchar(3) comment ''
    ,match_price_decimal_local numeric(1,0) comment ''
    ,match_price_decimal_foreign numeric(1,0) comment ''
    ,primary_id_expiry_date timestamp comment ''
    ,secondary_id_expiry_date timestamp comment ''
    ,mgn_int_tdr_spread_pct numeric(5,2) comment ''
    ,mgn_base_int_rate numeric(5,2) comment ''
    ,mgn_int_tdr_share numeric(5,2) comment ''
    ,islamic_flag varchar(1) comment ''
    ,mcd_resident_flag varchar(1) comment ''
    ,chq_charges_flag varchar(1) comment ''
    ,chq_charges_tdr_pct numeric(9,2) comment ''
    ,brokerage_type_foreign_etrade varchar(3) comment ''
    ,brokerage_type_foreign_etrade_b varchar(3) comment ''
    ,brokerage_type_foreign_etrade_s varchar(3) comment ''
    ,grp_exch_code varchar(5) comment ''
    ,bdebt_ras varchar(1) comment ''
    ,twse_declaration varchar(1) comment ''
    ,joint_acc_amt numeric(12,2) comment ''
    ,high_risk_market varchar(2) comment ''
    ,brokerage_type_leap_normal varchar(3) comment ''
    ,brokerage_type_leap_etrade varchar(3) comment ''
    ,etl_timestamp  string comment 'ETL_processing_time'
    ,perm_country varchar(3) comment '' -- 20250715
    ,type_of_account string comment ''  -- added in 20250806
    ,einvoice_email string comment '' --20250902
)
comment 'mhbos customer information'
partitioned by (
    etl_dt string comment 'partition_by_day'
)
stored as parquet
tblproperties(
    'parquet.compression'='SNAPPY'
    ,'external.table.purge'='true'
)
;