INSERT OVERWRITE DIRECTORY '/data/output/ailab/${batch_date}/cur/cur_ailab_dm_account_f.${batch_date}.dat'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\001'
LINES TERMINATED BY '\n'
NULL DEFINED AS ''
SELECT
	REPLACE(REPLACE(ACCOUNT_ID,CHR(13),''),CHR(10),'') AS ACCOUNT_ID
	,REPLACE(REPLACE(SOURCE_ACCOUNT_ID,CHR(13),''),CHR(10),'') AS SOURCE_ACCOUNT_ID
	,REPLACE(REPLACE(SOURCE_NAME,CHR(13),''),CHR(10),'') AS SOURCE_NAME
	,REPLACE(REPLACE(ACCOUNT_STATUS,CHR(13),''),CHR(10),'') AS ACCOUNT_STATUS
	,REPLACE(REPLACE(ACCOUNT_CATEGORY,CHR(13),''),CHR(10),'') AS ACCOUNT_CATEGORY
	,REPLACE(REPLACE(CUSTOMER_ID,CHR(13),''),CHR(10),'') AS CUSTOMER_ID
	,REPLACE(REPLACE(ACCOUNT_NAME_FULL,CHR(13),''),CHR(10),'') AS ACCOUNT_NAME_FULL
	,REPLACE(REPLACE(ACCOUNT_TYPE,CHR(13),''),CHR(10),'') AS ACCOUNT_TYPE
	,REPLACE(REPLACE(ACCOUNT_CLIENT_TYPE,CHR(13),''),CHR(10),'') AS ACCOUNT_CLIENT_TYPE
	,REPLACE(REPLACE(CLR_ACCOUNT_ID,CHR(13),''),CHR(10),'') AS CLR_ACCOUNT_ID
	,REPLACE(REPLACE(ISLAMIC_FLAG,CHR(13),''),CHR(10),'') AS ISLAMIC_FLAG
	,REPLACE(REPLACE(AGENT_ID,CHR(13),''),CHR(10),'') AS AGENT_ID
	,REPLACE(REPLACE(HOME_BRANCH_ID,CHR(13),''),CHR(10),'') AS HOME_BRANCH_ID
	,REPLACE(REPLACE(CDS_ACCOUNT_ID,CHR(13),''),CHR(10),'') AS CDS_ACCOUNT_ID
	,REPLACE(REPLACE(DISPATCH_MODE,CHR(13),''),CHR(10),'') AS DISPATCH_MODE
	,ACCOUNT_CREATION_DATE AS ACCOUNT_CREATION_DATE
	,ACCOUNT_CLOSED_DATE AS ACCOUNT_CLOSED_DATE
	,REPLACE(REPLACE(JOMPAY_REFERENCCE_CODE,CHR(13),''),CHR(10),'') AS JOMPAY_REFERENCCE_CODE
	,REPLACE(REPLACE(ACCOUNT_PROHIBITION_TYPE,CHR(13),''),CHR(10),'') AS ACCOUNT_PROHIBITION_TYPE
	,ACCOUNT_PROHIBITION_DATE AS ACCOUNT_PROHIBITION_DATE
	,REPLACE(REPLACE(ACCOUNT_PROHIBITION_USER_ID,CHR(13),''),CHR(10),'') AS ACCOUNT_PROHIBITION_USER_ID
	,REPLACE(REPLACE(ACCOUNT_PROHIBITION_REMARKS,CHR(13),''),CHR(10),'') AS ACCOUNT_PROHIBITION_REMARKS
	,REPLACE(REPLACE(TRADING_ACCOUNT_PRODUCT_TYPE,CHR(13),''),CHR(10),'') AS TRADING_ACCOUNT_PRODUCT_TYPE
	,REPLACE(REPLACE(LINE_OF_BUSINESS,CHR(13),''),CHR(10),'') AS LINE_OF_BUSINESS
	,REPLACE(REPLACE(ACCOUNT_PAYEE_NAME,CHR(13),''),CHR(10),'') AS ACCOUNT_PAYEE_NAME
	,REPLACE(REPLACE(ACCOUNT_REMARKS_1,CHR(13),''),CHR(10),'') AS ACCOUNT_REMARKS_1
	,REPLACE(REPLACE(ACCOUNT_REMARKS_2,CHR(13),''),CHR(10),'') AS ACCOUNT_REMARKS_2
	,REPLACE(REPLACE(ACCOUNT_REMARKS_3,CHR(13),''),CHR(10),'') AS ACCOUNT_REMARKS_3
	,REPLACE(REPLACE(ACCOUNT_STOP_PAYMENT_FLAG,CHR(13),''),CHR(10),'') AS ACCOUNT_STOP_PAYMENT_FLAG
	,REPLACE(REPLACE(JOINT_ACCOUNT_FLAG,CHR(13),''),CHR(10),'') AS JOINT_ACCOUNT_FLAG
	,REPLACE(REPLACE(SUB_ACCOUNT_FLAG,CHR(13),''),CHR(10),'') AS SUB_ACCOUNT_FLAG
	,REPLACE(REPLACE(NOMINEES_TYPE,CHR(13),''),CHR(10),'') AS NOMINEES_TYPE
	,REPLACE(REPLACE(PLEDGED_SECURITIES_FLAG,CHR(13),''),CHR(10),'') AS PLEDGED_SECURITIES_FLAG
	,REPLACE(REPLACE(PRINCIPAL_NAME,CHR(13),''),CHR(10),'') AS PRINCIPAL_NAME
	,REPLACE(REPLACE(INTERMEDIARY_NAME,CHR(13),''),CHR(10),'') AS INTERMEDIARY_NAME
	,REPLACE(REPLACE(BENEFICIARY_OWNER_NAME,CHR(13),''),CHR(10),'') AS BENEFICIARY_OWNER_NAME
	,REPLACE(REPLACE(BENEFICIARY_OWNER_ID_NO,CHR(13),''),CHR(10),'') AS BENEFICIARY_OWNER_ID_NO
	,REPLACE(REPLACE(BENEFICIARY_CUSTOMER_ID,CHR(13),''),CHR(10),'') AS BENEFICIARY_CUSTOMER_ID
	,REPLACE(REPLACE(ACCOUNT_APPLICATION_SOURCE,CHR(13),''),CHR(10),'') AS ACCOUNT_APPLICATION_SOURCE
	,DCO_ONBOARD_DATE AS DCO_ONBOARD_DATE
	,REPLACE(REPLACE(LAST_TRANSACTION_DATE,CHR(13),''),CHR(10),'') AS LAST_TRANSACTION_DATE
	,REPLACE(REPLACE(CDS_BRANCH_CODE,CHR(13),''),CHR(10),'') AS CDS_BRANCH_CODE
	,REPLACE(REPLACE(ACCOUNT_ATTRIBUTE,CHR(13),''),CHR(10),'') AS ACCOUNT_ATTRIBUTE
	,REPLACE(REPLACE(ACCOUNT_ATTRIBUTE_TYPE,CHR(13),''),CHR(10),'') AS ACCOUNT_ATTRIBUTE_TYPE
	,REPLACE(REPLACE(ACCOUNT_CLIENT_GROUP,CHR(13),''),CHR(10),'') AS ACCOUNT_CLIENT_GROUP
	,REPLACE(REPLACE(W8BEN,CHR(13),''),CHR(10),'') AS W8BEN
	,W8BEN_EXPIRY_DATE AS W8BEN_EXPIRY_DATE
	,REPLACE(REPLACE(ACCOUNT_ENTITY,CHR(13),''),CHR(10),'') AS ACCOUNT_ENTITY
	,REPLACE(REPLACE(ACCOUNT_CLASSIFICATION,CHR(13),''),CHR(10),'') AS ACCOUNT_CLASSIFICATION
    , '${batch_timestamp}' AS ETL_TIMESTAMP
    , ETL_DT
FROM ${cur_schema}.dim_account T
WHERE T.etl_dt = '${batch_date}'
AND SOURCE_NAME NOT IN ('TOMS', 'MUSASHI');

-- FileName:   /data/output/ailab/${batch_date}/cur/cur_ailab_dm_account_f.${batch_date}.dat