output_path=/data/input/${batch_date}/${src_sys}
output_file=${src_sys}_${src_table_name}_${if_mark}.${batch_date}.${file_type}

fra_connected_parties=/data/input/fra/ConnectedParties_Data_${batch_date}.TXT
guava_branch=/data/input/guava/EXTERNAL_BRANCH_${batch_date}.TXT
guava_branch_contact=/data/input/guava/EXTERNAL_BRANCH_CONTACT_${batch_date}.TXT
guava_company=/data/input/guava/EXTERNAL_COMPANY_${batch_date}.TXT
toms_reference_lookup=/data/input/toms/TOMS_reference_lookup.txt
general_reference_lookup=/data/input/general/GENERAL_reference_lookup.txt
general_bank=/data/input/general/GENERAL_bank.txt
mhbos_reference_lookup=/data/input/mhbos/MHBOS_reference_lookup.txt
lookup_custname_primaryidno=/data/input/lookup/lookup_custname_primaryidno.csv
lookup_custname_custname=/data/input/lookup/lookup_custname_custname.csv
lookup_clientno_custname=/data/input/lookup/lookup_clientno_custname.csv
lookup_primaryidno_newcustname=/data/input/lookup/lookup_primaryidno_newcustname.csv
rak_reference_lookup=/data/input/rak/RAK_reference_lookup.txt
rak_customer=/data/input/rak/RAKCUST_${batch_date}.dat
rak_trx_my=/data/input/rak/RAKTRX_MY_${batch_date}.dat
rak_trx_hk=/data/input/rak/RAKTRX_HK_${batch_date}.dat
rak_trx_us=/data/input/rak/RAKTRX_US_${batch_date}.dat
kdi_customer=/data/input/kdi/KDICUST_${last_date}.dat
kdi_trx=/data/input/kdi/KDITRX_${last_date}.dat
m21_a_customer=/data/input/m21/M21_A_CUST_${last_date}.dat
m21_o_customer=/data/input/m21/M21_O_CUST_${last_date}.dat
m21_a_trx=/data/input/m21/M21_A_TRX_${last_date}.dat
m21_o_trx=/data/input/m21/M21_O_TRX_${last_date}.dat
general_country=/data/input/general/GENERAL_COUNTRY.txt