
source: k2

default_model: 3b


column_rules:
    non_original_fields:
        name: ["etl_timestamp", "start_dt", "end_dt", "part_id"]

temp_table_rules:
    backup_table:
        suffix: _bk
        action: skip
    history_table:
        suffix: _bf
        action: skip
    new_write_table:
        suffix: _nw
        action: skip
    unchange_table:
        suffix: _od
        action: skip


