
source: mhbos

default_model: 3a

default_key:
    - client_no

column_rules:
    non_original_fields:
        name: ["etl_timestamp", "start_dt", "end_dt", "part_id", "etl_dt"]


temp_table_rules:
    backup_table:
        temp_table_name_suffix: _bk
        action: skip
    history_table:
        temp_table_name_suffix: _bf
        action: skip
    new_write_table:
        temp_table_name_suffix: _nw
        action: skip
    unchange_table:
        temp_table_name_suffix: _od
        action: skip